{ inputs, config, lib, pkgs, fop-utils, ... }@args:
let
  inherit (lib) mkEnableOption mkIf recursiveUpdate;
  inherit (builtins) fromJSON unsafeDiscardStringContext readFile;

  cfg = config.flake-configs.dank-material-shell;

  cursor = {
    package = pkgs.kdePackages.breeze;
    name = "Breeze_Light";
    size = 24; # For wayland
  };

  flat-remix-icons = (pkgs.flat-remix-icon-theme.overrideAttrs (old: rec {
    version = "20251119";
    src = pkgs.fetchFromGitHub {
      owner = "daniruiz";
      repo = "flat-remix";
      rev = version;
      sha256 = "sha256-tQCzxMz/1dCsPSZHJ9bIWCRjPi0sS7VhRxttzzA7Tr4=";
    };
  }));
in
{
  imports = [
    inputs.dms.homeModules.dank-material-shell
    inputs.dms.homeModules.niri
    inputs.dms-plugin-registry.modules.default
  ]
  ++ (map (mod: (import mod (args // { inherit cfg; }))) [
    ./niri
  ]);

  options.flake-configs.dank-material-shell = {
    enable = mkEnableOption "Dank Material Shell";
  };

  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      flat-remix-icons
      kdePackages.breeze
      kdePackages.breeze-gtk

      # Theming support
      libsForQt5.qt5ct
      kdePackages.qt6ct

      # Fallback theme for vivaldi
      adwaita-qt6
    ];

    gtk = {
      enable = true;
      theme = {
        name = "Breeze";
        package = pkgs.kdePackages.breeze-gtk;
      };
      iconTheme = {
        name = "Flat-Remix-Orange-Dark";
        package = flat-remix-icons;
      };
      gtk3.extraConfig = {
        gtk-application-prefer-dark-theme = 1;
      };
      gtk4.extraConfig = {
        gtk-application-prefer-dark-theme = 1;
      };
    };

    qt = rec {
      enable = true;
      # style.name = "kvantum"; # Don't force so qtct is happy, and especially so stuff doesn't crash
      platformTheme.name = "qt6ct";
      qt6ctSettings = {
        Appearance = {
          color_scheme_path = "${config.home.homeDirectory}/.config/qt6ct/colors/matugen.conf";
          custom_palette = true;
          icon_theme = config.gtk.iconTheme.name;
          standard_dialogs = "default";
          style = "Breeze";
        };
      };
      qt5ctSettings = recursiveUpdate qt6ctSettings {
        Appearance.color_scheme_path = "${config.home.homeDirectory}/.config/qt5ct/colors/matugen.conf";
      };

      # Actually what the shit
      kde.settings = rec {
        kdeglobals = {
          General.ColorScheme = "DankMatugenDark";
          UiSettings.ColorScheme = kdeglobals.General.ColorScheme;
          Icons.Theme = config.gtk.iconTheme.name;
        };
        dolphinrc = {
          UiSettings.ColorScheme = kdeglobals.General.ColorScheme;
        };
      };
    };

    home.pointerCursor = {
      package = cursor.package;
      name = cursor.name;
      size = cursor.size;
      gtk.enable = true;
      x11.enable = true;
    };
    home.sessionVariables = {
      NIXOS_OZONE_WL = 1;
    };

    programs.dank-material-shell = {
      enable = true;

      settings = recursiveUpdate
        (fromJSON (unsafeDiscardStringContext (readFile ./settings.json)))
        {
          # FIXME
          # theme = "dark";
          # dynamicTheming = true;

          # Remap the theme, likely on export it'll point to the registry
          currentThemeCategory = "custom";
          currentThemeName = "custom";
          customThemeFile = pkgs.writeText "theme.json" (
            builtins.toJSON (import ./theme.nix args)
          );
        };

      session = recursiveUpdate
        (fromJSON (unsafeDiscardStringContext (readFile ./session.json)))
        {
          isLightMode = false;
        };

      clipboardSettings = {
        maxHistory = 25;
        maxEntrySize = 5242880;
        autoClearDays = 1;
        clearAtStartup = true;
        disabled = false;
        disableHistory = false;
        disablePersist = true;
      };

      niri = {
        enableKeybinds = false;
        enableSpawn = false; # systemd managed

        includes = {
          enable = true; # Enable config includes hack. Enabled by default.

          override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
          originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
          filesToInclude = [
            # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
            "alttab" # Please note that niri will throw an error if any of these files are missing.
            "binds"
            "colors"
            "cursor"
            "layout"
            "outputs"
            "windowrules"
            "wpblur"
          ];
        };
      };
    };
  };
}
