# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:
{
  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "nvme"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    kernelModules = [ "kvm-intel" ];
    blacklistedKernelModules = [ "xe" ];

    # Hopefully resolve issues with text and images being funny
    # kernelParams = [
    # # NOTE: these didn't do anything
    #   "i915.enable_psr=0"
    #   "i915.enable_fbc=0"
    # ];

    initrd.luks.devices."nixmain".device = "/dev/disk/by-uuid/9674ab8d-e58c-4b73-8d76-9037799010a2";
  };

  services.fwupd.enable = true;
  hardware.bluetooth.enable = true;

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      intel-compute-runtime
      vpl-gpu-rt
    ];
    extraPackages32 = with pkgs; [
      driversi686Linux.intel-media-driver
    ];
  };

  environment.systemPackages = with pkgs; [
    intel-gpu-tools
  ];

  swapDevices =
    [{
      device = "/.swapfile";
      size = 32 /*GB*/ * 1024;
    }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
