{ lib, cfg, ... }@args:
let
  inherit (lib) mkIf;

  # Helper to apply mkForce on every attribute, in this case binds.
  # If a bind is defined here at all, it will use the config here even if it has a default
  mkForceBinds = binds:
    lib.mapAttrs (_: v: lib.mkForce v) binds;
in
{
  imports = (map (mod: (import mod (args // { inherit cfg; }))) [
    ./default-keybinds.nix
  ]);

  config = mkIf cfg.enable {
    programs.dank-material-shell = {
      niri = {
        enableSpawn = false; # Handled with systemd
        enableKeybinds = false;

        includes = {
          enable = true; # Enable config includes hack. Enabled by default.

          override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
          originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
          filesToInclude = [
            # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
            "alttab" # Please note that niri will throw an error if any of these files are missing.
            "binds"
            "colors"
            "cursor"
            "layout"
            "outputs"
            "windowrules"
            "wpblur"
          ];
        };
      };

      plugins = {
        niriWindows.enable = true;
      };
    };

    programs.niri.settings = {
      input = {
        mouse = {
          accel-profile = "flat";
          accel-speed = -0.8;
        };

        focus-follows-mouse = {
          enable = true;
          max-scroll-amount = "10%";
        };

        keyboard = {
          xkb = {
            layout = "us,cz";
            variant = "mac,qwerty-mac";
          };
        };
      };

      binds = mkForceBinds {
        "Super+Space".action.switch-layout = "next";
        "Super+Alt+L" = {
          action.spawn = [ "dms" "ipc" "call" "lock" "lock" ];
          hotkey-overlay.title = "Lock Screen";
          repeat = false;
          allow-inhibiting = false;
        };
        "Super+Alt+Ctrl+Shift+O" = {
          action.spawn = [ "dms" "ipc" "spotlight" "toggle" ];
          hotkey-overlay.title = "(Super): Toggle Application Launcher";
          repeat = false;
          allow-inhibiting = false;
        };
        "Mod+E" = {
          action.spawn = [ "dolphin" ];
          hotkey-overlay.title = "Launch Dolphin";
          repeat = false;
          allow-inhibiting = false;
        };
        "Mod+T" = {
          action.spawn = [ "konsole" ];
          hotkey-overlay.title = "Launch Konsole";
          repeat = false;
          allow-inhibiting = false;
        };
        "Mod+N" = {
          action.spawn = [ "dms" "ipc" "call" "notepad" "toggle" ];
          hotkey-overlay.title = "Notepad: Toggle";
          repeat = false;
          allow-inhibiting = false;
        };
        "Mod+V" = {
          action.spawn = [ "dms" "ipc" "call" "clipboard" "toggle" ];
          hotkey-overlay.title = "Clipboard: Toggle";
          repeat = false;
          allow-inhibiting = false;
        };
        "Mod+Ctrl+F" = {
          action.maximize-window-to-edges = { };
          hotkey-overlay.title = "Maximize Window";
          repeat = false;
          allow-inhibiting = false;
        };

        # Media
        "XF86AudioPlay" = {
          action.spawn = [ "dms" "ipc" "call" "mpris" "playPause" ];
          hotkey-overlay.hidden = true;
          allow-when-locked = true;
          repeat = false;
          allow-inhibiting = false;
        };
        "XF86AudioPrev" = {
          action.spawn = [ "dms" "ipc" "call" "mpris" "previous" ];
          hotkey-overlay.hidden = true;
          allow-when-locked = true;
          repeat = false;
          allow-inhibiting = false;
        };
        "XF86AudioNext" = {
          action.spawn = [ "dms" "ipc" "call" "mpris" "next" ];
          hotkey-overlay.hidden = true;
          allow-when-locked = true;
          repeat = false;
          allow-inhibiting = false;
        };

        # Audio
        "XF86AudioLowerVolume" = {
          action.spawn = [ "dms" "ipc" "call" "audio" "decrement" "5" ];
          hotkey-overlay.hidden = true;
          repeat = true;
          allow-inhibiting = false;
          allow-when-locked = true;
        };
        "XF86AudioRaiseVolume" = {
          action.spawn = [ "dms" "ipc" "call" "audio" "increment" "5" ];
          hotkey-overlay.hidden = true;
          repeat = true;
          allow-inhibiting = false;
          allow-when-locked = true;
        };
      };

      hotkey-overlay.skip-at-startup = true;
    };
  };
}
